language: ruby

rvm:
  - 2.3.1

env:
  - DB=postgresql

before_script:
  - cp config/application.example.yml config/application.yml
  - psql -c 'create database womenrising_test' -U postgres
  - psql -c 'create database womenrising_development' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

