language: ruby

rvm:
  - 2.2.3

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

before_script:
  - cp config/application.example.yml config/application.yml
  - psql -c 'create database womenrising_test' -U postgres
